apiVersion: v1
kind: Secret
metadata:
  name: smart-roommate-secrets
  namespace: smart-roommate
type: Opaque
stringData:
  DATABASE_URL: REPLACE_IN_SECRET_STORE
  JWT_SECRET: REPLACE_IN_SECRET_STORE
  REFRESH_TOKEN_SECRET: REPLACE_IN_SECRET_STORE
  AZURE_STORAGE_CONNECTION_STRING: REPLACE_IN_SECRET_STORE
  AZURE_SERVICE_BUS_CONNECTION_STRING: REPLACE_IN_SECRET_STORE

