apiVersion: v1
kind: Service
metadata:
  name: smart-roommate-api
  namespace: smart-roommate
spec:
  selector:
    app: smart-roommate-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

